feat: first version of the app
UNDP-Data/sdg-labelling-app pull request #1
Opened 2023-04-24 10:47 UTC by Guille-lg

# Summary

This pull request contains the first version of the app, with basic functionality to label different sdg paragraphs.

2023-05-01 13:45 UTC, mykolaskrynnyk commented on assets/UNDP_logo.svg.png
@Guille-lg , the official emblem should not be present either in the repository or in the application.

2023-05-02 10:23 UTC, Guille-lg commented
@mykolaskrynnyk fixed the issues with the logo and requirements file, ready for review

2023-05-02 10:31 UTC, Guille-lg commented
@mykolaskrynnyk fixed the issues with the logo and requirements file. For some reason, the requirements file commit still shows the file as binary, but when checking out the branch the file is fine. May need additional review.

2023-05-02 13:16 UTC, mykolaskrynnyk requested changes
@Guille-lg , once the comments are resolved, the request will be merged.

2023-05-02 13:16 UTC, mykolaskrynnyk commented on scripts/components.py
> +            ),
Do not use the official emblem in the app.

2023-05-02 13:16 UTC, mykolaskrynnyk commented on scripts/database.py
> +    load_dotenv()
No need to use `load_dotenv` inside functions. Just include this call in the `app.py`. The env variables will then be available throughout the application anyway.

2023-05-02 13:16 UTC, mykolaskrynnyk commented on scripts/database.py
> +    load_dotenv()
```suggestion
```

2023-05-02 13:16 UTC, mykolaskrynnyk commented on assets/UNDP_logo.svg.png
@Guille-lg , this can be removed now too.

2023-05-02 14:06 UTC, Guille-lg commented
Fixed the load_dotenv and UNDP logo issues

2023-05-02 14:10 UTC, merged